In [1]:
print('hello world')

hello world


**модуль math**

In [6]:
import math
# округление
a = 3.2
print(math.ceil(a), math.floor(a))
# модуль
a = -7
print(math.fabs(a))
# остаток от деления
a = 7
b = 8
print(math.fmod(a, b))
# степень
print(math.pow(a, b))
# корень квадратный
print(math.sqrt(b))
# корень кубический
print(math.pow(b, 1/3))
# экспонента
print(math.exp(b))
math.pow(math.e, b)
# логарифм
math.log(a, b)
# a=-7
# b=6
# math.log(a, b)
c=100
d=4
print(math.log2(d))
print(math.log10(c))
# тригонометрические функции
x = math.pi/3
print(math.cos(x))
print(math.sin(x))
print(math.tan(x))
# факториал
print(math.factorial(b))
#  домашнее задание: Ответьте, как сконвертировать градусы в радианы и наоборот. Сделайте это.
x=30
y=math.radians(x)
print(math.radians(x))
print(math.degrees(y))

4 3
7.0
7.0
5764801.0
2.8284271247461903
2.0
2980.9579870417283
2.0
2.0
0.5000000000000001
0.8660254037844386
1.7320508075688767
40320
0.5235987755982988
29.999999999999996


**модуль NumPy**

In [ ]:
import numpy as np
# массив
a = np.array([2, 3, 4, 5])
type(a)
a.shape
# двумерный массив
b = np.array([
    [45, 67, 23, 12], 
    [56, 89, 24, 53]])
b
b.shape
# массив нулей
a=np.zeros((4, 6))
a
# массив единиц
a=np.ones((2, 4, 5))
a
# единичная
a=np.eye(6)
a
# наполненная мусором
a=np.empty((4, 4))
a
# заполнение с шагом 5
a=np.arange(20, 40, 5)
a
a=np.arange(2, 0, -0.5)
print(a)
# инструкции по выводу чисел
np.set_printoptions(threshold=1000, precision=2)


# базовые операции numpy
a=np.array([20, 30, 40, 50])
b=np.arange(4)
c = a+b
print(c)

c = a-b
print(c)

c = a*b
print(c)

c = a/b
print(c)
# бесконечность
print(np.inf+np.inf)
print(-1*np.inf)
print(np.inf*np.inf)
print(np.inf-np.inf)
# не число
print(np.nan+np.nan)
print(-1*np.nan)
print(np.nan*np.nan)
print(np.nan-np.nan)
# поэлементное возведение в степень и остаток 
print(a**b)
print(a%b)


# тригонометрический блок
print(np.cos(a))
print(np.arctan(a))
print(np.tan(a))
c=5*np.cos(a) #
c
np.round(c,2)
print(c)
np.ceil(c)
print(c)
np.fix(c)
print(c)


# агрегатные функции
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a))
print(a.sum)
print(a.min)
print(a.max)
# минимальное по столбцам
print(a.min(axis=1))
# по строкам
print(a.min(axis=0))


# срезы, индексация
a = np.arange(10) ** 4
a
print(a)
a[0]
a[2:7]
a[[7,3]]
print(a[[7,7]])
a[3:5] = 2
print(a)
print(a[::-1])
# срезы индексация двумерный массив
b=np.array([np.arange(4), 
           np.arange(4) ** 3,
           np.arange(4) * 5, 
           np.arange(4) * 11,
           np.arange(4) + 2])
print(b)
print(b[2, 3])
print(b[[2, 3], 3])
print(b[2:4,1:4])

c=b.transpose()
print(c)

print(c.reshape((5, 4)))
print(1)




[2.  1.5 1.  0.5]
[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[  inf 30.   20.   16.67]
inf
-inf
inf
nan
nan
nan
nan
nan
[     1     30   1600 125000]
[0 0 0 2]
[ 0.41  0.15 -0.67  0.96]
[1.52 1.54 1.55 1.55]
[ 2.24 -6.41 -1.12 -0.27]
[ 2.04  0.77 -3.33  4.82]
[ 2.04  0.77 -3.33  4.82]
[ 2.04  0.77 -3.33  4.82]
21
<built-in method sum of numpy.ndarray object at 0x0000020C03CBFB70>
<built-in method min of numpy.ndarray object at 0x0000020C03CBFB70>
<built-in method max of numpy.ndarray object at 0x0000020C03CBFB70>
[1 4]
[1 2 3]
[   0    1   16   81  256  625 1296 2401 4096 6561]
[2401 2401]
[   0    1   16    2    2  625 1296 2401 4096 6561]
[6561 4096 2401 1296  625    2    2   16    1    0]
[[ 0  1  2  3]
 [ 0  1  8 27]
 [ 0  5 10 15]
 [ 0 11 22 33]
 [ 2  3  4  5]]
15
[15 33]
[[ 5 10 15]
 [11 22 33]]
[[ 0  0  0  0  2]
 [ 1  1  5 11  3]
 [ 2  8 10 22  4]
 [ 3 27 15 33  5]]
[[ 0  0  0  0]
 [ 2  1  1  5]
 [11  3  2  8]
 [10 22  4  3]
 [27 15 33  5]]
1


C:\Users\podne\AppData\Local\Temp\ipykernel_24380\4156821318.py:45: RuntimeWarning: divide by zero encountered in divide
  c = a/b
C:\Users\podne\AppData\Local\Temp\ipykernel_24380\4156821318.py:59: RuntimeWarning: divide by zero encountered in remainder
  print(a%b)


**генерация случайных чисел**

In [28]:
import numpy as np
import numpy.random as rand
print(np.random.sample())
a=np.random.sample(5)
print(a)
b=np.random.sample((1, 1, 4))
print(b)
c=np.random.randint(0, 5, 10)
print(c)
d=np.random.randint(0, 3, (2, 10))
print(d)

np.random.seed(42)
print(np.random.random(10))
np.random.seed(100)
print(np.random.random(10))
np.random.seed(1000)
print(np.random.random(10))

0.20708234438674689
[0.74 0.39 0.18 0.74 0.07]
[[[0.89 0.95 0.93 0.42]]]
[4 3 4 3 0 4 2 2 4 0]
[[0 0 1 0 2 1 2 1 2 1]
 [1 2 1 0 1 0 0 2 2 1]]
[0.37 0.95 0.73 0.6  0.16 0.16 0.06 0.87 0.6  0.71]
[0.54 0.28 0.42 0.84 0.   0.12 0.67 0.83 0.14 0.58]
[0.65 0.12 0.95 0.48 0.87 0.21 0.04 0.4  0.23 0.84]
